tinyMCE.addI18n('pt.advanced_dlg',{
about_title:"Acerca de TinyMCE",
about_general:"Acerca de",
about_help:"Ajuda",
about_license:"Licen\u00E7a",
about_plugins:"Plugins",
about_plugin:"Plugin",
about_author:"Autor",
about_version:"Versao",
about_loaded:"Loaded plugins",
anchor_title:"Insert/edit anchor",
anchor_name:"Anchor name",
code_title:"Editor codigo HTML",
code_wordwrap:"Quebra de linha",
colorpicker_title:"Selecionar um color",
colorpicker_picker_tab:"Picker",
colorpicker_picker_title:"Color picker",
colorpicker_palette_tab:"Palette",
colorpicker_palette_title:"Palette colors",
colorpicker_named_tab:"Named",
colorpicker_named_title:"Named colors",
colorpicker_color:"Color:",
colorpicker_name:"Name:",
charmap_title:"Select custom character",
image_title:"Insert/edit image",
image_src:"URL da Imagem",
image_alt:"Descricao da Imagem",
image_list:"Lista de Imagens",
image_border:"Borders",
image_dimensions:"Dimensoes",
image_vspace:"Espa\u00E7o Vertical",
image_hspace:"Espa\u00E7o Horizontal",
image_align:"Alinhamento",
image_align_baseline:"Baseline",
image_align_top:"Top",
image_align_middle:"Middle",
image_align_bottom:"Bottom",
image_align_texttop:"Text top",
image_align_textbottom:"Text bottom",
image_align_left:"Esquerda",
image_align_right:"Direita",
link_title:"Inserir/editar hipervinculo",
link_url:"Hipervinculo URL",
link_target:"Target",
link_target_same:"Abrir hipervinculo na janela",
link_target_blank:"Abrir hipervinculo em nova janela",
link_titlefield:"Titulo",
link_is_email:"A URL parece ser um endereço email, deseja adicionar o prefixo requerido mailto:?",
link_is_external:"A URL parece um hipervinculo externo, deseja adicionar o prefixo http:// ?",
link_list:"Lista de hipervinculos"
});
